[package]
name = "html-layout"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
html-dom = { path = "../html-dom" }
html-style-model = { path = "../html-style-model" }
hypher = "0.1"
kurbo.workspace = true
rustc_data_structures = "0.1.2"
taffy.workspace = true
unicode_categories = "0.1"
unicode-segmentation = "1.13"

[dev-dependencies]
html-parse = { path = "../html-parse" }
html-style = { path = "../html-style" }
lightningcss.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
